servos: 

- id: 3
  joint_name: j1_torso
  model_name: H54-100-S500-R
  name: H54
  model_number: 00003
  cpr: 501900 
  gear_reduction: 500.0
  max_vel_value: 17000.0
  max_vel_rads: 2.921688
  joint_type: prismatic
#  min_rad: 1.5
#  max_rad: -16.0
  min_rad: 7.5
  max_rad: -10.0
  min_m: 0.0
  max_m: 0.3342
# Links limits with digital inputs to avoid movement
  lim_sw_pos: 2
  lim_sw_neg: 3

- id: 13
  joint_name: j1_head
  model_name: L42
  name: L42
  model_number: 00047
  cpr: 4096 
  gear_reduction: 300.0
  max_vel_value: 400.0
  max_vel_rads: 2.98452
  joint_type: revolute
  min_rad: -1.5708
  max_rad: 1.5708

- id: 12
  joint_name: j2_head
  model_name: L42
  name: L42
  model_number: 00048
  cpr: 4096
  gear_reduction: 300.0
  max_vel_value: 400.0
  max_vel_rads: 2.98452
  joint_type: revolute
  min_rad: -0.7854
  max_rad: 0.7854
  

