servos: 

- id: 3
  joint_name: j1_torso
  model_name: H54-100-S500-R
  name: H54
  model_number: 00003
  cpr: 501900
  gear_reduction: 500.0
  max_vel_value: 17000.0
  max_vel_rads: 2.921688
  joint_type: prismatic
  min_rad: 9.0
  max_rad: -9.0
  min_m: 0.0
  max_m: 0.3438

